project:
  type: website
  output-dir: docs

website:
  title: "Probability & Statistics at DSBA"

  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: "Module 1"
        menu:
          - text: "Seminar 1: Basics of Combinatorics"
            href: Seminar_1.qmd
          - text: "Problem Set 1"
            href: problem_set_01.qmd

          - text: "---"

          - text: "Seminar 2: Probabilistic Models"
            href: seminar_2.qmd
          - text: "Problem Set 2"
            href: problem_set_02.qmd

          - text: "---"

          - text: "Seminar 3: Bayes' Theorem"
            href: seminar_3.qmd
          - text: "Problem Set 3"
            href: problem_set_03.qmd

          - text: "---"

          - text: "Seminar 4: Discrete Random Variables"
            href: seminar_4.qmd
          - text: "Problem Set 4"
            href: problem_set_04.qmd

          - text: "---"

          - text: "Seminar 5: Expectation and Variance"
            href: seminar_5.qmd
          - text: "Problem Set 5"
            href: problem_set_05.qmd

          - text: "---"

          - text: "Seminar 6: Covariance, Correlation and WLLN"
            href: seminar_6.qmd
          - text: "Problem Set 6"
            href: problem_set_06.qmd

          - text: "---"

          - text: "Seminar 7: Continuous Random Variables"
            href: seminar_7.qmd
          - text: "Problem Set 7"
            href: problem_set_07.qmd

      - text: "Module 2"
        menu:
          - text: "Coming soon"

      - text: "Module 3"
        menu:
          - text: "Coming soon"

      - text: "Module 4"
        menu:
          - text: "Coming soon"

      - href: resources.qmd
        text: Resources
     
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-fold: true
    code-summary: "Show Python code"
    smooth-scroll: true
    number-sections: true
