project:
  type: website
  output-dir: docs

website:
  title: "Probability Theory"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: lectures.qmd
        text: Lectures
      - href: seminars.qmd
        text: Seminars

format:
  html:
    theme: cosmo
    toc: true
    number-sections: true

