Welcome to the seminar materials for the course **Probability & Statistics** in the **HSE DSBA** programme.

## Seminars - Module 1

- **Seminar 1: Basics of Combinatorics**  
  [Theory Review](seminars/Seminar_1.html) · [Problem Set](problems/problem_set_01.html)

- **Seminar 2: Probabilistic Models**  
  [Theory Review](seminars/seminar_2.html) · [Problem Set](problems/problem_set_02.html)

- **Seminar 3: Bayes' Theorem**  
  [Theory Review](seminars/seminar_3.html) · [Problem Set](problems/problem_set_03.html)

- **Seminar 4: Discrete Random Variables**  
  [Theory Review](seminars/seminar_4.html) · [Problem Set](problems/problem_set_04.html)

- **Seminar 5: Expectation and Variance of Discrete Random Variables**  
  [Theory Review](seminars/seminar_5.html) · [Problem Set](problems/problem_set_05.html)

- **Seminar 6: Covariance, Correlation and the Weak Law of Large Numbers**  
  [Theory Review](seminars/seminar_6.html) · [Problem Set](problems/problem_set_06.html)

- **Seminar 7: Continuous Random Variables. Normal Distribution**  
  [Theory Review](seminars/seminar_7.html) · [Problem Set](problems/problem_set_07.html)

## Seminars - Module 2

- **Seminar 8: Random Vectors. Distributions derived from Normal distribution**  
  [Theory Review](seminars/Seminar_8.html) · [Problem Set](problems/problem_set_08.html)

- **Seminar 9: Expectation. Moment Generating Functions**  
  [Theory Review](seminars/seminar_9.html) · [Problem Set](problems/problem_set_09.html)

- **Seminar 10: CLT. Limit theorems**  
  [Theory Review](seminars/seminar_10.html) · [Problem Set](problems/problem_set_10.html)

- **Seminar 11: Point Estimators and their Properties**  
  [Theory Review](seminars/seminar_11.html) · [Problem Set](problems/problem_set_11.html)

- **Seminar 12: MLE & Method of Moments**  
  [Theory Review](seminars/seminar_12.html) · [Problem Set](problems/problem_set_12.html)

- **Seminar 13: Efficiency and the Cramer-Rao Lower Bound**  
  [Theory Review](seminars/seminar_13.html) · [Problem Set](problems/problem_set_13.html)

- **Seminar 14: Sufficient Statistics & Exponential families**  
  [Theory Review](seminars/seminar_14.html) · [Problem Set](problems/problem_set_14.html)


## Additional Information

Information about grading, homework, deadlines, and course announcements is available in the [Course Information](course_information.qmd) section.

Additional materials, including statistical tables, cheat sheets, and other useful resources, can be found in the [Resources](resources.qmd) section.
